[tool.poetry]
name = "non-overlapping-rules-ensemble"
version = "0.1.0"
description = ""
authors = ["Bogdan Gulowaty <b.gulowaty@gmail.com>"]
readme = "README.md"
packages = [{include = "note"}]

[tool.pytest.ini_options]
python_files = "*.py"
norecursedirs=["libs"]

[tool.poetry.dependencies]
python = "^3.10"
x-to-rules = {path = "libs/rules", develop = true}
networkx = "^2.8.7"
sympy = "^1.11.1"
python-box = "*"
numba = "^0.59.1"
datasetz = {path = "../datasets", develop = true}
imbalanced-learn = "^0.12.2"
ml-utils = {path = "../ml-utils"}

[tool.poetry.group.dev.dependencies]
jupyterlab = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
